### PR TITLE
Convert tabs to spaces if expandtab is false

### PR DESCRIPTION
**Pull request by kalmiz**
Some interpreters - for example the Scala REPL - cannot handle directly
inserted tabs.

### CODE REVIEW

**Comment by habamax** [comment]
Could you rename `sendtoterm_tab2space` to `sendtoterm_expandtab`?

Do you think it should be "on" by default?

**Comment by kalmiz** [comment]
Rename is done.

I think "on" should be the default because you can control it with the 'expandtab' option as well.

**Comment by habamax** [comment]
Well, I have noexpandtab and with your defaults all tabs will be replaced by spaces.

I was asking about whether we should have 'as-is' text to be sent to terminal by default (sendterm_expandtab = 0) or not.

I am not sure what is the best way here, let us have it the way you did for now.

**Comment by habamax** [comment]
Thx!

**Comment by kalmiz** [comment]
Yep, that's the expected behavior. You have noexpandtab, which means that you indent with tabs, so for example, if you have a simple `if` condition like this:
```bash
if [ "$name" ]; then
	echo "Hello $name!"
else
	echo "Hello stranger!"
fi
``` 
then you cannot send it to bash because it will try to tab complete the `\t` chars. Basically, I'd agree that we should send text 'as-is' to terminal but in some case it makes unusable your otherwise great and simple plugin :)

**Comment by habamax** [comment]
Ahh, yes indeed. That is make sense.

**Pull request merged**
